version: '3.8'

services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: DockerFile
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./BACKEND
      dockerfile: DockerFile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "3000:3000"
